Lambda support
reilabs/lampe pull request #16
Opened 2024-11-15 10:23 UTC by utkn

**This PR is a work in progress.**

Closes #6

2024-11-28 17:05 UTC, kustosz requested changes
Some changes needed, but this awesome! I'm glad this works and turned out so nice

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe.lean
> +  let add = |a, b|: Field, Field -> Field { #add(a, b) : Field };
Can we make the syntax `|a: Field, b: Field| -> Field { ... }`?

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe.lean
> +  fun v => v = x + y := by
some work to do on this proof, but let's revisit this later

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Ast.lean
> +inductive FunctionIdent {rep : Tp → Type} : Type where
Pretty sure this shouldn't be implicit. It can't be auto-inferred (as evidenced by the fact that the only use in this PR has it called with `@`

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Ast.lean
> +structure Lambda where
This is very copy-pasty with `Function`. Probably the most direct way to fix would be to make `Function` into
```
structure Function where
  generics : List Kind
  body : HList Kind.denote generics -> Lambda
```

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Hoare/SepTotal.lean
> +def STHoare p Γ P e (Q : Tp.denote p tp → SLP (State p))
I love that `SLP` doesn't depend on `p` anymore, it was horrible

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Hoare/SepTotal.lean
> +  (h_hoare_imp : STHoare p Γ P e₁ Q → STHoare p Γ (P ⋆ H) e₂ (fun v => Q v ⋆ H))
This assumption is always true, this is literally baking in the frame rule

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Hoare/SepTotal.lean
> +  STHoare p Γ H e₂ Q := by
This theorem is just `consequence_frame_left` with H1 set to P and H2 set to H

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Semantics.lean
> +inductive Omni : (p : Prime) → Env → State p → Expr (Tp.denote p) tp → (Option (State p × Tp.denote p tp) → Prop) → Prop where
what was wrong with the variable on line 11?

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/Semantics.lean
> +    have hd₁ : Finmap.Disjoint lmbs (Finmap.singleton r lambda) := by
All of this set-fu needs to become lemmas, way too much repetition in this code. Let's rush features first, but please open an issue to fix these up when we have time

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/SeparationLogic/LawfulHeap.lean
> +theorem LawfulHeap_union_empty_commutative [LawfulHeap α] {a : α} :
All of these should become namespaces instead of prefixes, like `LawfulHeap.union_empty_commutative`

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/SeparationLogic/LawfulHeap.lean
> +theorem LawfulHeap_union_empty_commutative [LawfulHeap α] {a : α} :
Also make it `comm` nobody has time to write `commutative` :D

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/SeparationLogic/State.lean
> +notation:max "[" l " ↣ " r "]" => State.lmbSingleton l r
Not a fan of this notation, these arrows are hard to see. I propose `[ \lam l \map r]`. This way we keep the arrow and clearly say "this is a lambda sir"

2024-11-28 17:05 UTC, kustosz commented on Lampe/Lampe/SeparationLogic/ValHeap.lean
> +-- def ValHeap.singleton (r : Ref) (v : AnyValue p) : SLP (ValHeap p) := fun st => st = Finmap.singleton r v
rm

2024-11-28 18:34 UTC, utkn commented on Lampe/Lampe.lean
> +  let add = |a, b|: Field, Field -> Field { #add(a, b) : Field };
I had tried this but couldn't get it to work. But now I was able to do it.

2024-11-28 18:37 UTC, utkn commented on Lampe/Lampe/Semantics.lean
> +    have hd₁ : Finmap.Disjoint lmbs (Finmap.singleton r lambda) := by
Issue opened #19

2024-12-02 12:31 UTC, kustosz approved these changes

2024-12-02 12:31 UTC, kustosz commented on Lampe/Lampe.lean
> +  try (exact _)
the `try` here doesn't do anything

2024-12-02 12:38 UTC, merged